
-- ==========================  TABLES  =====================--

CREATE TABLE STR_POOL (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(128)
);

CREATE TABLE UUSER_ABS (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  FULLNAME VARCHAR(64),
  EMAIL VARCHAR(128) UNIQUE,
  TOKEN VARCHAR(64),
  HOST VARCHAR(128),
  PASSWORD VARCHAR(128) DEFAULT '$2a$10$3NTPya6TN.11/VLxBhJjBekgWOmV.Y.OvvQOjy9y07hiNEKjQPp5S',
  PERMISSION_ID BIGINT(16) DEFAULT 1,
  DTYPE VARCHAR(8) DEFAULT 'UUser'
);

CREATE TABLE PERMISSION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  APP_USER_ID BIGINT(16),
  REF_TYPE VARCHAR(32),
  REF_ID BIGINT(16),
  TYPE VARCHAR(32),
  ORIGIN_USER_ID BIGINT(16),
  GRANTED_FROM_USER_ID BIGINT(16),
  CONSTRAINT FK_PERMISSION_USER FOREIGN KEY (USER_ID) REFERENCES UUSER_ABS(ID),
  CONSTRAINT FK_PERMISSION_ORIGIN FOREIGN KEY (ORIGIN_USER_ID) REFERENCES UUSER_ABS(ID),
  CONSTRAINT FK_PERMISSION_GRANTED FOREIGN KEY (GRANTED_FROM_USER_ID) REFERENCES UUSER_ABS(ID)
);

CREATE TABLE USER_PHOTO (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  APP_USER_ID BIGINT(16),
  POSITION TINYINT,
  URL VARCHAR(256),
  CONSTRAINT FK_USER_PHOTO FOREIGN KEY (USER_ID) REFERENCES UUSER_ABS(ID)
);


CREATE TABLE REMARK(
  ID BIGINT(16) PRIMARY KEY,
  POSTER_ID BIGINT(16),
  CONVERSATION_ID BIGINT(16),
  CONTENT LONGTEXT,
  TIME_STAMP DATETIME(6),
  CONSTRAINT FK_POSTER_REMARK FOREIGN KEY (POSTER_ID) REFERENCES UUSER_ABS(ID)
);

CREATE TABLE HAS_READ(
  REMARK_ID BIGINT(16),
  USER_ID BIGINT(16),
  CONSTRAINT FK_REMARK_HAS_READ FOREIGN KEY (REMARK_ID) REFERENCES REMARK(ID),
  CONSTRAINT FK_USER_HAS_READ FOREIGN KEY (USER_ID) REFERENCES UUSER_ABS(ID),
  CONSTRAINT COMP_PK_HAS_READ PRIMARY KEY (REMARK_ID, USER_ID)
);

CREATE TABLE COLLAPSE_USER(
  FOR_USER_ID BIGINT(16),
  TARGET_USER_ID BIGINT(16),
  CONSTRAINT FK_FOR_USER FOREIGN KEY (FOR_USER_ID) REFERENCES UUSER_ABS(ID),
  CONSTRAINT FK_TARGET_USER FOREIGN KEY (TARGET_USER_ID) REFERENCES UUSER_ABS(ID),
  CONSTRAINT COMP_PK_COLLAPSE_USER PRIMARY KEY (FOR_USER_ID, TARGET_USER_ID)
);

CREATE TABLE APP (
  ID BIGINT(16) PRIMARY KEY,
  ACCESS_KEY VARCHAR(64),
  NAME VARCHAR(64),
  HOST VARCHAR(128),
  PROTECTED_APP_ID VARCHAR(64) NULL,
  TOKEN_EXPIRATION BIGINT(16) DEFAULT 999999999999999
);

-- ==========================  AUTHORIZE  =====================--

CREATE TABLE AUTHORIZED_APP_USER (
  APP_ID BIGINT(16),
  USER_ID BIGINT(16),
  CONSTRAINT COMP_PK_AUTH_APP_USERS PRIMARY KEY (APP_ID, USER_ID),
  CONSTRAINT FK_AUTH_APP_USER_USER FOREIGN KEY (USER_ID) REFERENCES UUSER_ABS(ID),
  CONSTRAINT FK_AUTH_APP_USER_APP FOREIGN KEY (APP_ID) REFERENCES APP(ID)
);

CREATE TABLE ACCESS_TOKEN (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  OBJECT_ID BIGINT(16),
  TOKEN VARCHAR(64),
  DTYPE VARCHAR(32),
  EXPIRATION BIGINT(16) NOT NULL,
  DEVICE_IDENTIFIER VARCHAR(64) NOT NULL
);

CREATE TABLE USER_TOKEN (
  USER_ID BIGINT(16),
  DTYPE VARCHAR(32),
  TOKEN VARCHAR(64),
  DEVICE_IDENTIFIER VARCHAR(64) NOT NULL,
  EXPIRATION BIGINT(16) NOT NULL,
  CONSTRAINT COMP_PK_USER_TOKEN PRIMARY KEY (USER_ID, DEVICE_IDENTIFIER, DTYPE)
);

CREATE TABLE RULE (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  APP_ID BIGINT(16),
  APP_EXCLUSION INT(1) DEFAULT 1,
  USER_EXCLUSION INT(1) DEFAULT 1,
  ENDPOINT_REG_EXP VARCHAR(128),
  CONSTRAINT FK_GATE_APP FOREIGN KEY (APP_ID) REFERENCES APP(ID)
);

CREATE TABLE USER_RULE (
  RULE_ID BIGINT(16),
  USER_ID BIGINT(16),
  CONSTRAINT COMP_PK_USER_RULE PRIMARY KEY (RULE_ID, USER_ID),
  CONSTRAINT FK_USER_RULE_RULE FOREIGN KEY (RULE_ID) REFERENCES RULE(ID),
  CONSTRAINT FK_USER_RULE_USER FOREIGN KEY (USER_ID) REFERENCES UUSER_ABS(ID)
);

CREATE TABLE APP_RULE (
  RULE_ID BIGINT(16),
  APP_ID BIGINT(16),
  CONSTRAINT COMP_PK_USER_RULE PRIMARY KEY (RULE_ID, APP_ID),
  CONSTRAINT FK_APP_RULE_RULE FOREIGN KEY (RULE_ID) REFERENCES RULE(ID),
  CONSTRAINT FK_APP_RULE_APP FOREIGN KEY (APP_ID) REFERENCES APP(ID)
);

-- ==========================  OBJECT_ACCESS  =====================--

CREATE TABLE OBJECT_ACCESS (
  ID BIGINT(16) PRIMARY KEY,
  NICK_NAME_ID BIGINT(16) NULL,
  OBJECT_TYPE_ID BIGINT(16),
  ACCESS_REFERENCE_ID BIGINT(16),
  OBJECT_ID BIGINT(16),
  DTYPE VARCHAR(16),
  CONSTRAINT FK_OBJECT_TYPE_NAME_STR_POOL FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES STR_POOL(ID)
  CONSTRAINT FK_OBJECT_NICK_NAME_STR_POOL FOREIGN KEY (NICK_NAME_ID) REFERENCES STR_POOL(ID)
);

CREATE TABLE FIELD (
  ID BIGINT(16) PRIMARY KEY,
  OBJECT_ACCESS_ID BIGINT(16),
  FIELD_NAME_ID BIGINT(16),
  ACCESS_TYPE INT(1),
  CONSTRAINT FK_FIELDS_OBJECT FOREIGN KEY (OBJECT_ACCESS_ID) REFERENCES OBJECT_ACCESS(ID),
  CONSTRAINT FK_FIELDS_STR_POOL FOREIGN KEY (FIELD_NAME_ID) REFERENCES STR_POOL(ID)
);

CREATE TABLE USER_GROUP (
  ID BIGINT(16) PRIMARY KEY,
  DTYPE VARCHAR(16),
  REFERENCE_ID BIGINT(16),
  NICK_NAME_ID VARCHAR(32),
  CONSTRAINT FK_USER_GROUP_NAME_STR_POOL FOREIGN KEY (NICK_NAME_ID) REFERENCES STR_POOL(ID)
);

CREATE TABLE USER_GROUP_MEMEBERS (
    USER_GROUP_ID BIGINT(16),
    EMAIL VARCHAR(128),
    CONSTRAINT FK_USER_MEMBERS_USER_GROUP FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP(ID)
);

CREATE TABLE USER_GROUP_GROUPS (
    USER_GROUP_ID BIGINT(16),
    LINKED_USER_GROUP_ID BIGINT(16),
    CONSTRAINT FK_USER_MEMBERS_USER_GROUP FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP(ID),
    CONSTRAINT FK_USER_MEMBERS_LINKED_USER_GROUP FOREIGN KEY (LINKED_USER_GROUP_ID) REFERENCES USER_GROUP(ID)
);


-- ==================== Reference Tables ============================ --

CREATE TABLE UUSER_SERVERS (
  HOST VARCHAR(128),
  USER_HITS BIGINT(16) DEFAULT 0,
  APP_HITS BIGINT(16) DEFAULT 0
);

CREATE TABLE UUSER_REFERENCES (
  USER_EMAIL VARCHAR(128),
  HOST VARCHAR(128)
);

CREATE TABLE APP_REFERENCE (
  APP_ID BIGINT(16),
  HOST VARCHAR(128)
);

-- ==================== Object Permission Tables ============================ --

CREATE TABLE SCOPE (
  ID INT(1) PRIMARY KEY,
  VALUE VARCHAR(16) UNIQUE
);

CREATE TABLE FIELD_NAME (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(16) UNIQUE
);

CREATE TABLE OBJECT_NAME (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(16) UNIQUE
);

CREATE TABLE FIELD_SCOPE (
  USER_ID BIGINT(16),
  APP_ID BIGINT(16),
  OBJECT_NAME_ID BIGINT(16),
  FIELD_NAME_ID BIGINT(16),
  SCOPE_ID INT(1),
  CONSTRAINT COMP_PK_FIELD_SCOPE PRIMARY KEY (USER_ID, APP_ID, OBJECT_NAME_ID, FIELD_NAME_ID),
  CONSTRAINT FK_FIELD_SCOPE_USER FOREIGN KEY (USER_ID) REFERENCES UUSER_ABS(ID),
  CONSTRAINT FK_FIELD_SCOPE_APP FOREIGN KEY (APP_ID) REFERENCES APP(ID),
  CONSTRAINT FK_FIELD_SCOPE_OBJECT FOREIGN KEY (OBJECT_NAME_ID) REFERENCES OBJECT_NAME(ID),
  CONSTRAINT FK_FIELD_SCOPE_FIELD FOREIGN KEY (FIELD_NAME_ID) REFERENCES FIELD_NAME(ID),
  CONSTRAINT FK_FIELD_SCOPE_SCOPE FOREIGN KEY (SCOPE_ID) REFERENCES SCOPE(ID)
);

CREATE TABLE DEFAULT_SCOPE (
  OBJECT_NAME_ID BIGINT(16),
  FIELD_NAME_ID BIGINT(16),
  SCOPE_ID INT(1),
  CONSTRAINT COMP_PK_FIELD_SCOPE PRIMARY KEY (OBJECT_NAME_ID, FIELD_NAME_ID, SCOPE_ID),
  CONSTRAINT FK_DEFAULT_SCOPE_OBJECT FOREIGN KEY (OBJECT_NAME_ID) REFERENCES OBJECT_NAME(ID),
  CONSTRAINT FK_DEFAULT_SCOPE_FIELD FOREIGN KEY (FIELD_NAME_ID) REFERENCES FIELD_NAME(ID),
  CONSTRAINT FK_DEFAULT_SCOPE_SCOPE FOREIGN KEY (SCOPE_ID) REFERENCES SCOPE(ID)
);

CREATE OR REPLACE VIEW APP_FIELD_SCOPE AS
  SELECT FS.USER_ID, FS.APP_ID, FS.OBJECT_NAME_ID, FS.FIELD_NAME_ID,
      FIELD.VALUE AS FIELD, SCOPE.VALUE AS SCOPE,
      DS.VALUE AS DEFAULT_SCOPE
    FROM FIELD_SCOPE AS FS
    JOIN FIELD_NAME AS FIELD ON FIELD_NAME_ID = FIELD.ID
    JOIN SCOPE ON FS.SCOPE_ID = SCOPE.ID
    JOIN DEFAULT_SCOPE ON
      FS.OBJECT_NAME_ID = DEFAULT_SCOPE.OBJECT_NAME_ID AND
      FS.FIELD_NAME_ID = DEFAULT_SCOPE.FIELD_NAME_ID AND
      FS.SCOPE_ID = DEFAULT_SCOPE.SCOPE_ID
    JOIN SCOPE AS DS ON DS.ID = DEFAULT_SCOPE.SCOPE_ID;
