
--==========================  USERS  =====================--

DROP USER &2 CASCADE;

CREATE USER &2
IDENTIFIED BY &1
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT connect to &2;
GRANT resource to &2;
GRANT CREATE SESSION TO &2;
GRANT CREATE TABLE TO &2;
GRANT CREATE VIEW TO &2;
GRANT CREATE MATERIALIZED VIEW TO &2;
GRANT DEBUG CONNECT SESSION TO &2;
GRANT DEBUG ANY PROCEDURE TO &2;
GRANT create session to &2;
ALTER APP_USER &2 QUOTA 10m ON users;

conn &2/&1
