
--==========================  SEQUENCES  =====================--

CREATE SEQUENCE USER_ID_SEQ START WITH 1050;
CREATE SEQUENCE REMARK_ID_SEQ START WITH 1250;
CREATE SEQUENCE PHOTO_ID_SEQ START WITH 13350;
