
--==========================  TABLES  =====================--

CREATE TABLE APP_USER (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(64),
  EMAIL VARCHAR2(128) UNIQUE,
  TOKEN VARCHAR2(64),
  PASSWORD VARCHAR(128),
  CANT_MODIFY NUMBER(1) DEFAULT 0,
  PHOTO BLOB
);

CREATE TABLE REMARK(
  ID NUMBER PRIMARY KEY,
  POSTER_ID NUMBER,
  CONVERSATION_ID NUMBER,
  CONTENT CLOB,
  TIME_STAMP TIMESTAMP,
  CONSTRAINT FK_POSTER_REMARK FOREIGN KEY (POSTER_ID) REFERENCES APP_USER(ID)
);

CREATE TABLE FIELD (
  NAME VARCHAR2(256) PRIMARY KEY,
  TYPE VARCHAR2(64),
  DESCRIPTION VARCHAR2(1024)
);

CREATE TABLE HAS_READ(
  REMARK_ID NUMBER,
  APP_USER_ID NUMBER,
  CONSTRAINT FK_REMARK_HAS_READ FOREIGN KEY (REMARK_ID) REFERENCES REMARK(ID),
  CONSTRAINT FK_APP_USER_HAS_READ FOREIGN KEY (APP_USER_ID) REFERENCES APP_USER(ID),
  CONSTRAINT COMP_PK_HAS_READ PRIMARY KEY (REMARK_ID, APP_USER_ID)
);

CREATE TABLE COLLAPSE_APP_USER(
  FOR_APP_USER_ID NUMBER,
  TARGET_APP_USER_ID NUMBER,
  CONSTRAINT FK_FOR_APP_USER FOREIGN KEY (FOR_APP_USER_ID) REFERENCES APP_USER(ID),
  CONSTRAINT FK_TARGET_APP_USER FOREIGN KEY (TARGET_APP_USER_ID) REFERENCES APP_USER(ID),
  CONSTRAINT COMP_PK_COLLAPSE_APP_USER PRIMARY KEY (FOR_APP_USER_ID, TARGET_APP_USER_ID)
);

CREATE TABLE PERMISSION (
  NAME VARCHAR(256) PRIMARY KEY
);

CREATE TABLE REQUIRED (
  PERMISSION_NAME VARCHAR(256),
  FIELD_NAME VARCHAR(256),
  CONSTRAINT FK_PERMISSION_REQUIRED FOREIGN KEY (PERMISSION_NAME) REFERENCES PERMISSION(NAME),
  CONSTRAINT FK_FIELD_REQUIRED FOREIGN KEY (FIELD_NAME) REFERENCES FIELD(NAME),
  CONSTRAINT COMP_PK_REQUIRED PRIMARY KEY (PERMISSION_NAME, FIELD_NAME)
);

CREATE TABLE PERMISSION_INC_O_EX (
  APP_USER_ID NUMBER,
  PERMISSION_NAME VARCHAR(256),
  INCLUSION NUMBER(1) DEFAULT 0, -- 0 EXCLUSION, 1 INCLUSION
  CONSTRAINT COMP_PK_PG_INC PRIMARY KEY (APP_USER_ID, PERMISSION_NAME),
  CONSTRAINT FK_PG_INCOEX_APP_USER FOREIGN KEY (APP_USER_ID) REFERENCES APP_USER(ID),
  CONSTRAINT FK_PG_INCOEX_PERM FOREIGN KEY (PERMISSION_NAME) REFERENCES PERMISSION(NAME)
);
