
--==========================  TABLES  =====================--

CREATE TABLE AM_USER (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(64),
  EMAIL VARCHAR2(128) UNIQUE,
  USER_TOKEN VARCHAR2(64),
  PASSWORD VARCHAR(128),
  CANT_MODIFY NUMBER(1) DEFAULT 0,
  PHOTO BLOB
);

CREATE TABLE REMARK(
  ID NUMBER PRIMARY KEY,
  POSTER_ID NUMBER,
  CONVERSATION_ID NUMBER,
  CONTENT CLOB,
  TIME_STAMP TIMESTAMP,
  CONSTRAINT FK_POSTER_REMARK FOREIGN KEY (POSTER_ID) REFERENCES AM_USER(ID)
);

CREATE TABLE HAS_READ(
  REMARK_ID NUMBER,
  USER_ID NUMBER,
  CONSTRAINT FK_REMARK_HAS_READ FOREIGN KEY (REMARK_ID) REFERENCES REMARK(ID),
  CONSTRAINT FK_USER_HAS_READ FOREIGN KEY (USER_ID) REFERENCES AM_USER(ID),
  CONSTRAINT COMP_PK_HAS_READ PRIMARY KEY (REMARK_ID, USER_ID)
);

CREATE TABLE COLLAPSE_USER(
  FOR_USER_ID NUMBER,
  TARGET_USER_ID NUMBER,
  CONSTRAINT FK_FOR_USER FOREIGN KEY (FOR_USER_ID) REFERENCES AM_USER(ID),
  CONSTRAINT FK_TARGET_USER FOREIGN KEY (TARGET_USER_ID) REFERENCES AM_USER(ID),
  CONSTRAINT COMP_PK_COLLAPSE_USER PRIMARY KEY (FOR_USER_ID, TARGET_USER_ID)
);

CREATE TABLE PAGE (
  ID NUMBER PRIMARY KEY,
  IDENTIFIER VARCHAR(256) UNIQUE,
  JSON_OBJ BLOB DEFAULT '7b7d'
);

CREATE TABLE PAGE_INC_O_EX (
  USER_ID NUMBER,
  PAGE_IDENTIFIER VARCHAR(256),
  INCLUSION NUMBER(1) DEFAULT 0, -- 0 EXCLUSION, 1 INCLUSION
  CONSTRAINT COMP_PK_PG_INC PRIMARY KEY (USER_ID, PAGE_IDENTIFIER),
  CONSTRAINT FK_PG_INCOEX_USER FOREIGN KEY (USER_ID) REFERENCES AM_USER(ID),
  CONSTRAINT FK_PG_INCOEX_PAGE FOREIGN KEY (PAGE_IDENTIFIER) REFERENCES PAGE(IDENTIFIER)
);

CREATE TABLE USER_VERSION (
  USER_ID NUMBER,
  PAGE_IDENTIFIER VARCHAR2(256),
  JSON_OBJ BLOB DEFAULT '7b7d',
  TIME_STAMP TIMESTAMP,
  CONSTRAINT COMP_PK_USER_PAGE PRIMARY KEY (USER_ID, PAGE_IDENTIFIER),
  CONSTRAINT FK_VERSION_USER FOREIGN KEY (USER_ID) REFERENCES AM_USER(ID)
);

CREATE TABLE REVISION (
  ID NUMBER PRIMARY KEY,
  USER_ID NUMBER,
  PAGE_IDENTIFIER VARCHAR2(256),
  JSON_OBJ BLOB DEFAULT '7b7d',
  TIME_STAMP TIMESTAMP,
  CONSTRAINT FK_REVISION_USER FOREIGN KEY (USER_ID) REFERENCES AM_USER(ID)
);
