--==========================  PROCEDURES  =====================--

create or replace PROCEDURE ADD_FIELD(COLUMN_NAME IN VARCHAR2, COLUMN_TYPE IN VARCHAR2, DESCRIPTION IN VARCHAR2)
    IS
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE APP_USER ADD ' || COLUMN_NAME || ' ' || COLUMN_TYPE;
        INSERT INTO FIELD (NAME, DESCRIPTION, TYPE) VALUES (COLUMN_NAME, DESCRIPTION, COLUMN_TYPE);
    END;
/
